# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PortalEditor' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PortalEditor
  pod 'SwiftLint'
	pod 'Contentful', '~> 5.0.0'

  target 'PortalEditorTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PortalEditorUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
