# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'ZwanzigAR' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ZwanzigAR
  pod 'Contentful'
  pod 'ContentfulPersistenceSwift', '~> 0.13.0'
end
